AWSTemplateFormatVersion: '2010-09-09'
{{for:instances, file:subTemplates/instance.yaml}}
Resources:
  {{for:instances, file:subTemplates/instance.yaml}}
  NotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
      - {{for:instances, file:subTemplates/instance.yaml}}
      - Endpoint:
          Ref: {{proto}}
        Protocol: {{proto}}
      - {{file:subTemplates/aThing.yaml}}
  ELBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow access to the ELB
      VpcId:
        Ref: VPCID
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '80'
        ToPort: '80'
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: '443'
        ToPort: '443'
        CidrIp: {{cidr}}
Outputs:
  ELBDNSName:
    Description: ELB DNS Name
    Value:
      Fn::GetAtt:
      - ElasticLoadBalancer
      - DNSName